spring:
  application:
    name: cb3
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false  # 开发环境关闭缓存
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 12450
image:
  download:
    cache-path: "./cache/images/dev"
    max-cache-size: 1000
