spring:
  application:
    name: cb3
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false  # 开发环境关闭缓存
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 12450
app:
  cache-path: "./cache"
  max-cache-cover-size: 1000

